# -*- coding: utf-8 -*-
"""Day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MqAaxVj2qx64GgMAFzmkmLEMwd13zM5
"""

print("hii")

# Python Operators
a=2
print(a)

b=4
print(b)

a=5 #Overwrite
print(a)

a=2;
b=2
print(a==b) #equal operator


# DataTypes in python

#numerical datatypes
#1. Int
#2. Float
a=5
print(type(a))

b=5.0
print(type(b))

#string
d="Welcome"
print(type(d))

str1="1132333" #number in "" are considered as String
print(type(str1))
print(int(str1))
print(type(int(str1)) )#Typeconversion

#Boolean DataType
print(type(True))
print(type(False))


# List
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

list2=["ravi","3",2,4,5,"b",6.0]
print(list2)
print(type(list2))

list1=[1,2,3,4,5] #[1,2,6,4,5]

#list1[3]=6 #indexing start from 0
list1[2]=6

print(list1)

list1[-1]=7 #-ve indexing
print(list1)

list1.append(10)
print(list1)

list2=[9,8,7,6]
# list1.append(list2)
# list1

print(list1 + list2)

list1.extend(list2)
print(list1)


# Tuple
tuple1=(1,2,3,4,5)
print(tuple1)
print(type(tuple1))

tuple2=("ravi","3",2,4,5,"b",6.0)
print(tuple2)
print(type(tuple2))


# Dictionary [key-value pair]
dic1={"ravi":"SDE","algorithm":"Artist"}
print(dic1)
print(dic1["ravi"])
print(dic1["algorithm"])

dic1["ravi"]="Data Scientist"
print(dic1["ravi"])


#If-Else Statement
a=10
b=12
if(a>b):
    print("a is greater")
else:
    print("b is greater")

#For Loop python
list1=[1,2,3,4,5,6]
for num in list1:
    print(num)